language: python
dist: focal
python:
  - "3.8"
# command to install dependencies
services:
- postgresql

env:
  jobs:
    - DB_TEST_NAME="travis_ci_test" DB_PORT="5433"
  global:
    - PGPORT=5433

before_install:
  # Use trust instead of peer authentication:
  - >-
    sudo sed -i
    -e '/local.*peer/s/postgres/all/'
    -e 's/peer\|md5/trust/g'
    /etc/postgresql/12/main/pg_hba.conf
  # Restart the PostgreSQL service:
  - sudo service postgresql@12-main restart

addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12-postgis-3


install:
  - pip install -r requirements.txt


before_script:
 - sudo psql -p $PGPORT -c 'create database travis_ci_test;' -U postgres
 - sudo psql -p $PGPORT -c "create extension postgis;" -U postgres travis_ci_test

script:
  - python manage.py test

notifications:
  email:
    recipients:
      - andrei.avram@albascout.ro
    on_success: never
    on_failure: always

#deploy:
#
#  - provider: script
#    script: fab -H yeti.albascout.ro:24 -u scoutfile --password $DEPLOY_PASSWORD deploy_app
#    on:
#      branch: master
#    skip_cleanup: true
#
#  - provider: script
#    script: fab -H yeti.albascout.ro:24 -u scoutfile --password $DEPLOY_PASSWORD deploy_app
#    on:
#      branch: develop
#    skip_cleanup: true
#
