# Generated by Django 3.1.6 on 2021-02-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geogame', '0003_auto_20210216_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtowerchallenge',
            name='outcome',
            field=models.PositiveSmallIntegerField(choices=[(0, 'In asteptare'), (1, 'Confirmat'), (2, 'Respins')], default=0),
        ),
    ]
