# Generated by Django 3.1.6 on 2021-02-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geogame', '0004_auto_20210216_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tower',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Normal'), (2, 'RFID')]),
        ),
    ]
