# Generated by Django 3.1.6 on 2021-02-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geogame', '0005_auto_20210216_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='scoring_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Multe puncte la început, tot mai puține apoi'), (2, 'Putine puncte la început, tot mai multe apoi'), (3, 'Puncte proportional cu posesia'), (4, 'Putine punct la început, tot mai multe apoi (bonus)')]),
        ),
    ]
