# Generated by Django 3.1.6 on 2021-02-19 17:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geogame', '0009_auto_20210219_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
