# Generated by Django 3.1.6 on 2021-02-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geogame', '0010_team_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtowerchallenge',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
