# Generated by Django 3.1.6 on 2023-04-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geogame', '0013_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='initial_bonus',
            field=models.PositiveIntegerField(default=0, help_text='Număr inițial de puncte obținute la câștigarea turnului'),
        ),
    ]
