# Generated by Django 3.1.6 on 2023-04-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geogame', '0014_tower_initial_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='decrease_initial_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
